### ISSUE TITLE
Review Questions

### ISSUE THREAD

**Issue by meneal** [LambdaConglomerate/x9115lam#16] opened 2015-10-09 17:13 UTC
I'm just opening up an issue for this.  Kind of thinking it might make sense to work together in getting through these.  At least to come up with some sort of communal answer to them.  I'll start posting my answers this afternoon as I go through the questions.

**Comment by ghost** [comment] 2015-10-09 18:20
Sounds good to me. I have most of the first two done already, and I'm working on the next two for today.

**Comment by meneal** [comment] 2015-10-09 18:28
How much time are they taking?

**Comment by ghost** [comment] 2015-10-09 18:36
I'd say 45 minutes to an hour each. I had to look up a lot of definitions on the first one. The second one didn't take as long, though I did have to look up some syntax.

**Comment by ghost** [comment] 2015-10-10 15:39
I just pushed what I have for the first three reviews. I know the second one isn't finished. 

If there is something you disagree with, please let me know. Also, feel free to add any additional information you want. If it makes it clearer, we can put our initials beside each of our responses.

I'm hoping to have the second one and fourth one finished by the end of tonight.

**Comment by meneal** [comment] 2015-10-10 21:27
Thanks for doing that!  I'll be working on this some more this evening.  I've been really concentrating on HW6, but I really need to get on this too.

**Comment by meneal** [comment] 2015-10-11 20:33
There was a mistake in REVIEW2.md.  I just pushed a change.  I also pushed a runnable code block to show how it fails and a way to make it work.

**Comment by ghost** [comment] 2015-10-11 21:21
Looks like I misread the question. I thought it meant print lines that are longer than 20 characters, but he really just wants there to be more than 20 lines instead. I'm assuming there is no restriction on if blank lines are counted through. But good catch @meneal!

**Comment by meneal** [comment] 2015-10-12 00:24
Do you guys care if we just merge the two versions of REVIEW4?

**Comment by meneal** [comment] 2015-10-12 02:14
I've added some stuff as I went to the review questions and fixed stuff when I thought it was broken.  Hope you guys don't mind.

**Comment by meneal** [comment] 2015-10-12 14:56
I added review 7 up there.  Add whatever you want to it.

**Comment by aisobran** [comment] 2015-10-13 00:07
For Review 2 question 2c. You guys are both right.

Every function without a return, returns None. The function doesn't necessarily break, you cant call it with += syntactic sugar but it still works as intended if you use  **iadd**. Commenting it out disables method chaining but I suppose that's obvious.

**Comment by meneal** [comment] 2015-10-13 00:11
Oh shit.  I actually misread that.  I thought it meant what would happen if
you completely deleted the iadd funciton!

**Comment by aisobran** [comment] 2015-10-13 00:12
Either way you're right about += not working because it's self-referential

**Comment by ghost** [comment] 2015-10-13 01:33
Just a heads up, I made a slight change to Review6 where we had to label A and B in the figure. I understood it as what term best describes A and B (precision and recall). Let me know if you disagree.

**Comment by aisobran** [comment] 2015-10-13 12:07
@WumpaFruit Yeah that's right. 

Do you guys want to have a study session from 3:30 - 5:20 in the library?

**Comment by meneal** [comment] 2015-10-13 13:37
I'm into that.  Should we reserve a room?

**Comment by aisobran** [comment] 2015-10-13 14:11
I have 4322 reserved from 3:30 - 5:30

**Comment by ghost** [comment] 2015-10-13 15:23
I'll be there at 4.

**Comment by meneal** [comment] 2015-10-13 19:45
I'm up there now. Fire drill is over.

**Comment by ghost** [comment] 2015-10-13 19:46
Okay, I'm heading there too. Will be there in a few.

On Tue, Oct 13, 2015 at 3:45 PM, Matthew Neal notifications@github.com
wrote:

> I'm up there now. Fire drill is over.
> 
> On Tuesday, October 13, 2015, Joseph Sankar notifications@github.com
> wrote:
> 
> > I'll be there at 4.
> > On Oct 13, 2015 10:11 AM, "Alexander Sobran" <notifications@github.com
> > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> > wrote:
> > 
> > > I have 4322 reserved from 3:30 - 5:30
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> > 
> > https://github.com/LambdaConglomerate/x9115lam/issues/16#issuecomment-147726374
> > 
> > > .
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/LambdaConglomerate/x9115lam/issues/16#issuecomment-147749159
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/LambdaConglomerate/x9115lam/issues/16#issuecomment-147828843
> .

## 

_Joseph Sankar (About Me) http://josephsankar.me_
Master of Computer Science, Class of 2016, North Carolina State University
Bachelor's in Computer Science, Class of 2015, North Carolina State
University

**Comment by ghost** [comment] 2015-10-13 19:54
My card's not working on the door. Are you all in there?

**Comment by ghost** [comment] 2015-10-13 23:23
Closing this.

**Closed as completed by ghost** 2015-10-13 23:23 UTC
